name: 'Create-IOC-Files'
on:
  push:
    branches: ['research']
    paths: ['ioc.yaml', 'samples.csv', 'README.tpl']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Sync branches
      run: |
        git config --local user.name  ${{ github.actor }}
        echo "Checkout required files"
        git checkout origin/research -- ioc.yaml samples.csv README.tpl scripts
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build IOC Files
      run: |
          pip install -r scripts/requirements.txt
          python scripts/generate.py
    - name: Push changes
      run: |
        git add generated/
        git add ioc.yaml
        git add README.md
        git rm -rf -- README.tpl scripts
        git commit -m "Updating generated indicator files and README"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: master
