name: 'Lint with stalkerware-indicators-rs'
on:
  push:
    branches: ['master']
    paths: ['ioc.yaml', '.github/workflows/rust-linter.yml']
  pull_request:
    branches: [ 'master' ]
    paths: ['ioc.yaml', '.github/workflows/rust-linter.yml']

jobs:
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint ioc.yaml
      run: docker run -i --rm --init ghcr.io/kpcyrd/stalkerware-indicators-rs --dump-json /dev/stdin < ioc.yaml
